name = "r2-store"
main = "src/index.ts"
workers_dev = true
account_id = "2db2112b269ed3616ed3a863a222f3e8"
routes = [{ pattern = "r2-store.zshell.dev", custom_domain = true }]
compatibility_date = "2022-09-28"

[[r2_buckets]]
binding = "R2_STORE"
bucket_name = "r2-store"
preview_bucket_name = "r2-store-preview"
